#!/bin/sh
SERVICE=DOCKER
COMPOSE=$(docker compose version)
DOCKER=$(docker -v)
STATS=$(docker stats --no-stream)
PRINTF='# Servidor '$SERVICIO'
| Programa       | version                                |
| :--------------| :------------------------------------- |
| Docker         | '$DOCKER'   |
| Docker Compose | '$COMPOSE'         |


## Service Management '$SERVICE'
        systemct restart docker
        systemct stop docker
        systemct stary docker

## Servicios en ejecución
| Service        | Port      | Descripcion          | Service Name          |Ruta      |
| :------------- | :-------- | :------------------- | :-------------------- |:-------- |
| **Service**    | port      | Servidor Descripcion | Service.service       |/PATH/    |

**** [Container List] ****
'$STATS'
**** [Container List End] ****

## Documentation

[Docker](https://docs.docker.com/engine/)

'
printf '%s\n' "$PRINTF"
